### ISSUE TITLE
Prometheus setup integration?

### ISSUE THREAD

**Issue by elico** [jonpulsifer/dnsmon-go#2]
I have seen the image in the README.md and was wondering if there is any public setup instructions for a similar dashboard?

**Comment by jonpulsifer** [comment]
The public grafana documentation is probably the best place to get started, but it does make sense to publish a better example. https://prometheus.io/docs/visualization/grafana/

Would an example using docker compose be sufficient?

**Comment by jonpulsifer** [comment]
Ref the new README

A dashboard has been included to get you started using `docker-compose`.

1. `docker-compose up`
2. Navigate to `localhost:3000` and log in to Grafana using `admin:admin`
3. Generate some DNS queries using `docker-compose exec dnsmon-go nslookup example.com`
4. Watch the dashboard go brr

**Comment by elico** [comment]
yes of course a docker-compose examle is good.
I was talking about the json file..
