### ISSUE TITLE
在windows下如何使用

### ISSUE THREAD

**Issue by redmangame** [jonpulsifer/dnsmon-go#8]
你好，我的英文不行

C:\Users\hyx>C:\Go\my\src\dnsmon-go\dnsmon-go.exe
time="2021-05-27T16:30:23+08:00" level=info msg="Prometheus endpoint: http://0.0.0.0:8080/metrics"
time="2021-05-27T16:30:23+08:00" level=info msg="No flags specified, using defaults" promiscuous=true snaplen=65536
time="2021-05-27T16:30:23+08:00" level=info msg="Listening on device: \\Device\\NPF_{939EA951-33F0-482D-9F4C-A38B45D99B71}"

C:\Users\hyx>

运行就自动退出
另外可否增加http/https的请求url

**Comment by jonpulsifer** [comment]
你好！对不起我的中文不好

谢谢你的报告。

我不确定为什么它退出这么快。您确定选择了正确的接口吗？

`dnsmon-go` 仅支持 DNS。其他协议执行 DNS 查找，例如 SSH 或 GRPC，所以我不认为这会是一个很好的补充。
